services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
        arguments: ["@service_container", "@app.helper"]

    twig.twig_extension:
        class: AppBundle\Twig\TwigExtension
        tags:
          - { name: twig.extension }
        arguments: ["@service_container"]

    app.helper:
        class: AppBundle\Helper\AppHelper
        tags:
          - { name: app.helper }
        arguments: ["@service_container"]
